### ISSUE TITLE
Download error "MAC verification failed"

### ISSUE THREAD

**Issue by dautushenka** [qgustavor/megajs-cli#8] opened 2017-09-18 15:38 UTC
Nodejs 8.5.0  
megajs-cli 0.3.0  

I am not sure that error related to script, but I got this error on 2 different servers. Thanks

```
 ./node_modules/.bin/megajs dl https://mega.nz/#\!Nz5yCYQJ\!eTVR1LItKMjW0iCnA3PipWjTUD9Ddy8j9ebr9w2mnGk
TDRP72.rar: 0% - 63.63 KB of 812.34 MB
Error: MAC verification failed
    at Stream.end (/root/node_modules/megajs/dist/main.node-cjs.js:538:33)
    at _end (/root/node_modules/through/index.js:65:9)
    at Stream.stream.end (/root/node_modules/through/index.js:74:5)
    at Stream.onend (internal/streams/legacy.js:44:10)
    at emitNone (events.js:110:20)
    at Stream.emit (events.js:207:7)
    at Stream.<anonymous> (/root/node_modules/megajs/dist/main.node-cjs.js:55:10)
    at _end (/root/node_modules/through/index.js:65:9)
    at Stream.stream.end (/root/node_modules/through/index.js:74:5)
    at Stream.method [as end] (/root/node_modules/duplexer/index.js:47:39)
You can continue the download later using the --continue option
```

**Comment by dautushenka** [comment] 2017-09-18 16:26
Error depends on OS
with Debian 8 it works correctly.

Issue can be closed.

**Comment by qgustavor** [comment] 2017-09-18 17:11
Well, wait: this package uses [megajs](https://www.npmjs.com/package/megajs). In node it uses native crypto, in browser it uses a pure javascript implementation. There are unit tests to check if both implementations behave the same. Seems it's a problem on node, something [like this](https://stackoverflow.com/q/25340129), can you test on other node version?

**Comment by dautushenka** [comment] 2017-09-19 09:47
I've tested with different node versions and OS and figured out that it doesn't depend on them.
There are seem Mega has limitation or wrong response for some ips. 
I had been getting error before connected to OpenVPN on AWS. So now I see that it depends on source ip address. For downloading from mega website ip address doesn't matter.

**Comment by qgustavor** [comment] 2017-09-19 09:48
OK, so that's not a bug in Node or in the library. Issue closed.

**Comment by dautushenka** [comment] 2017-09-19 10:57
@qgustavor 
I've just tested other libraries and they work correct.
I tested official megacmd and unofficial old php library https://github.com/smartinm/mega-php-client

So I was able to download file from megacmd and mega-php, but megajs threw error

**Comment by dautushenka** [comment] 2017-09-19 13:05
So, if maxConnections is more than 1 I am getting error. We need investigate CombineStream usage
```
file.download({
    maxConnections: 2
},function(err, buffer) {
    if (err) throw err;
    console.log("DONE " + buffer.length);
});
```

**Comment by qgustavor** [comment] 2017-09-19 13:19
Reopening issue. I find it strange because I use this same library on directme.ga and in some projects (I'm downloading a file using it right now) and rarely this error happens.

**Comment by dautushenka** [comment] 2017-09-20 12:55
@qgustavor 
PR to fix it. Please merge, change version and push to npm
https://github.com/qgustavor/mega/pull/26
Thanks

**Comment by qgustavor** [comment] 2017-10-27 11:19
Closing issue as the bug was fixed.

**Closed as completed by qgustavor** 2017-10-27 11:19 UTC
